TankMeasure/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from Tank_Measurement import views

urlpatterns = [
    url(r'^menu/', views.NewMenu),
    url(r'^menu1/', views.NewMenu1),

    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),

    url(r'^Tank_Measurment/', include('Tank_Measurement.urls', namespace="Tank_Measurement")),

    url(r'', views.MainMenu, name='MainMenu'),
]

Tank_Measurement/urls.py
from django.conf.urls import url


from . import views
from . import views_kulindrikesdexamenes
from . import views_sfairikesdexamemes


from models import Kausima
from dal import autocomplete

app_name = 'Tank_Measurment'
urlpatterns = [
#    url(r'^$', views.index, name='index'),

#    url(r'^list/$', views.PublisherList.as_view(), name='list'),
    url(r'^list/$', views.KausimaList, name='list'),
    url(r'^listk/$', views.KausimaList, name='listKausima'),
    url(r'^editkaysima/(?P<pk>[0-9]+)/$', views.KausimaEdit.as_view(), name='edit'),

#    url(r'^listKD/$', views_kulindrikesdexamenes.KulindrikesDexamenesList, name='listKulDex'),
    url(r'^listKD/$', views_kulindrikesdexamenes.KulindrikesDexamenesDetailFiltered, name='listKulDex'),

    url(r'^createKD/$', views_kulindrikesdexamenes.KulindrikesDexamenesCreate.as_view(), name='createKulDex'),
    url(r'^editKD/(?P<pk>[0-9]+)/$', views_kulindrikesdexamenes.KulindrikesDexamenesEdit.as_view(), name='editKulDex'),

    url(r'^listSD/$', views_sfairikesdexamemes.SfairikesDexamemesList, name='listSfaDex'),
    url(r'^createSD/$', views_sfairikesdexamemes.SfairikesDexamemesCreate.as_view(), name='createSfaDex'),
    url(r'^editSD/(?P<pk>[0-9]+)/$', views_sfairikesdexamemes.SfairikesDexamemesEdit.as_view(), name='editSfaDex'),

    url(r'^calc/$', views.index),
    url(r'^crisp/$', views.FormF5ByTabView.as_view(), name='editSfaDex'),

    # url(r'^detail/(?P<pk>[0-9]+)/$', views.PeopleDetailView.as_view(), name='detail'),
    # url(r'^update/(?P<pk>[0-9]+)/$', views.PeopleUpdate.as_view(), name='update'),
    # url(r'^delete/(?P<pk>[0-9]+)/$', views.PeopleDelete.as_view(), name='delete'),
    # url(r'^create/$', views.PeopleCreare.as_view(), name='create'),
    # url(r'^listd/', views.doctor_list, name='doctor_list'),
    # url(r'^listp/', views.patient_list, name='patient_list'),


]

templates/NewMenu.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="el-gr" >


{% block content %}	

<!--This Does the Menu Play --!>
<link rel='stylesheet' id='style-css' href='https://bookdl.com/wp-content/themes/magaziner/style.css' type='text/css' media='all'/>
<!--Menu AutoWidth --!>
<link rel='stylesheet' id='responsive-css' href='https://bookdl.com/wp-content/themes/magaziner/responsive.css' type='text/css' media='all'/>
<!--Green Menu --!>
<!--<link rel='stylesheet' id='custom-css' href='https://bookdl.com/wp-content/themes/magaziner/custom.css' type='text/css' media='all'/>--!>

<div id="header-bottom">
<div class="container-inner group">
<nav class="nav-container group" id="nav-header">
<div class="nav-toggle"><i class="fa fa-bars"></i></div>
<div class="nav-text"> </div>
<div class="nav-wrap container"><ul id="menu-header" class="nav group"><li id="menu-item-9877" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9877"><a href="https://bookdl.com/category/arts-photography/">Arts &#038; Photography</a></li>
<li id="menu-item-9878" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9878"><a href="https://bookdl.com/category/business-money/">Business &#038; Money</a></li>
<li id="menu-item-9879" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9879"><a href="https://bookdl.com/category/computers-technology/">Computers &#038; Technology</a></li>
<li id="menu-item-9880" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9880"><a href="https://bookdl.com/category/cookbooks-food-wine/">Cookbooks, Food &#038; Wine</a></li>
<li id="menu-item-9881" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9881"><a href="https://bookdl.com/category/education-reference/">Education &#038; Reference</a></li>
<li id="menu-item-9882" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9882"><a href="https://bookdl.com/category/health-fitness/">Health &#038; Fitness</a></li>
<li id="menu-item-9883" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9883"><a href="https://bookdl.com/category/literature-fiction/">Literature &#038; Fiction</a></li>
<li id="menu-item-9884" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-9884"><a href="https://bookdl.com/category/others/">Others</a></li>
</ul></div>
</nav> 
</div> 
</div> 

{% endblock %}	

templates/NewMenuBootStrap.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="./NTD-Boot_files/favicon.ico">

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.1.1/css/bootstrap.css'%}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bootstrap-3.1.1/css/bootstrap-theme.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap-3.1.1/css/theme.css'%}" rel="stylesheet">
  </head>

  <body>
  
<nav class="navbar navbar-default">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"> <img alt="+" img-responsive src="{% static 'images/ExamHistory.png'%}"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
		    <li><a href="{% url "Tank_Measurement:list" %}">Καύσιμα</a></li>
		    <li><a href="{% url "Tank_Measurement:listKulDex" %}">Κυλινδρικές Δεξαμενές</a></li>
            <li><a href="{% url "Tank_Measurement:listSfaDex" %}">Σφαιρικές Δεξαμενές</a></li>
            <li><a href="{% url "Tank_Measurement:list" %}">Λίστα Εξετάσεων</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Άτομα<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li role="separator" class="divider"></li>
            <li><a href="{% url "Tank_Measurement:list" %}">Ασθενείς (Πίνακας)</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url "Tank_Measurement:list" %}">Ασθενείς (Λίστα)</a></li>
		    <li><a href="{% url "Tank_Measurement:list" %}">Ασθενείς (Λίστα2)</a></li>
			<li><a href="{% url "Tank_Measurement:list" %}">Ασθενείς (Λίστα3)</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Έξετάσεις<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url "Tank_Measurement:list" %}">Εξετάσεις</a></li>
            <li><a href="{% url "Tank_Measurement:list" %}">Εξετάσεις (Λίστα)</a></li>
            <li><a href="{% url "Tank_Measurement:list" %}">Προσθήκη Εξετάσεις</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Δίαφορα<span class="caret"></span></a>
          <ul class="dropdown-menu">
			<li><a href="{% url "Tank_Measurement:list" %}">  contact0</a></li>
			<li><a href="{% url "Tank_Measurement:list" %}">  contact1</a></li>
			<li><a href="{% url "Tank_Measurement:list" %}">  Locations</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Παραμετρικά<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url "Tank_Measurement:list" %}">Κατηγορία Φαρμάκων</a></li>
            <li><a href="{% url "Tank_Measurement:list" %}">Κατηγορία Εξέτασης</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Άλλα<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li role="separator" class="divider"></li>
            <li><a href="{% url "Tank_Measurement:list" %}">People Create</a></li>
            <li role="separator" class="divider"></li>
		    {#<li><a href="{% url "Tank_Measurement:list" %}">People List</a></li>
            <li role="separator" class="divider"></li>
		    <li><a href="{% url "Tank_Measurement:list" %}">Patient List</a></li>
		    <li><a href="{% url "Tank_Measurement:list" %}">Doctor List</a></li>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
   <div class="container theme-showcase" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Ογκομέτρηση Δεξαμενών.</h1>
        <p>απο Λ.Καπασακάλη.</p>
      </div>

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'bootstrap-3.1.1/js/jquery.js' %}"></script>
<script>window.jQuery | document.write('<script src="{% static 'bootstrap-3.1.1/js/jquery.min.js'%}"><\/script>')</script>
<script src="{% static 'bootstrap-3.1.1/js/bootstrap.js' %}"></script>



{% endblock content %}

templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% load crispy_forms_tags %}
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"el-gr" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}

    <link href="{% static 'bootstrap-3.1.1/css/bootstrap.css'%}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bootstrap-3.1.1/css/bootstrap-theme.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap-3.1.1/css/theme.css'%}" rel="stylesheet">


</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if not user.is_anonymous %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% if user.is_anonymous %}
        <a href="{% url 'login' %}">{% trans 'Log in' %}</a>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}

    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <!--<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>-->
    <a href="{% url 'MainMenu' %}">{% trans 'Home' %}</a>	
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}

    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">

        {% block pretitle %}{% endblock %}
        <!--{% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}--!>
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>

</body>
</html>

templates/baseMenu.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}
{% load example_app_tags %}
<!doctype html>

{% block content %}	
<html>
<head>
	{% if user.is_authenticated %}
	<p>Welcone, {{ user.username }} </p>
    <p>{{ people.name }} {{ people.surname }} {{ people.pk }}</p>
    <p>{{ altpeople.name }} {{ altpeople.surname }} {{ altpeople.pk }}</p>
	{% else %}
	<p>Welcome, new user. Please log in.</p>
	{% endif %}
    <title>{% block title %}
	Κεντρική σελίδα
	{% endblock title %}</title>
    {% block static %}
        {# jQuery #}
        <script src="{ static }} jquery-2.0.3.min.js"></script> 
<!--		<script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> --!>

        {# datatables.js #}
        <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
        <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.css">

        {# Bootstrap #}
        <link href="{{ static }} bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />
        <script src="{{ static }} bootstrap/3.1.1/js/bootstrap.min.js"></script>
		
<!---   <link href="{{ static }} bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />  ---!>
<!---   <script src="{{ static }} bootstrap/3.1.1/js/bootstrap.min.js"></script>   			 ---!>
		

        {# django-datatable-view #}
        <script type="text/javascript" charset="utf8" src="{{ STATIC }}js/datatableview.js"></script>
        <script type="text/javascript" charset="utf8">
            datatableview.auto_initialize = true;
        </script>

        {# code highlighting #}
        <link href="{{ static }}syntaxhighlighter/shCore.css" rel="stylesheet" type="text/css" />
        <link href="{{ static }}syntaxhighlighter/shThemeDefault.css" rel="stylesheet" type="text/css" />
        <script src="{{ static }}syntaxhighlighter/shCore.js" type="text/javascript"></script>
        <script src="{{ static }}syntaxhighlighter/shAutoloader.js" type="text/javascript"></script>
        <script src="{{ static }}syntaxhighlighter/shBrushPython.js" type="text/javascript"></script>

        {# test_project helpers #}
        <style type="text/css">
            .nav.sidebar a {
                border-right: 1px solid white;
                padding: 5px 10px;
            }
            .nav.sidebar a.active {
                font-weight: bold;
                background-color: #f0f0f0;
                border-color: #428bca;
            }
            .nav.sidebar li.divider {
                margin: 0.5em;
                border-top: 1px solid #dfdfdf;
            }
        </style>
        <script type="text/javascript">
            $(function(){
                SyntaxHighlighter.all();
                var path = window.location.pathname;
                $('.nav.sidebar > li > a[href="'+path+'"]').addClass("active");
            });
        </script>
    {% endblock static %}
</head>
<body>
    <div class="container">
        <br />
        <div class="row">
            <div class="col-md-3">
                <ul class="nav nav-list sidebar">
                    <li class="nav-list-item"><a href="{% url "examinations" %}">Εξετάσεις</a></li>
					<li class="nav-list-item"><a href="{% url "examination_list" %}">Εξετάσεις (Λίστα)</a></li>
					<li class="nav-list-item"><a href="{% url "examinationcreate" %}">Προσθήκη Εξετάσεις</a></li>
                    <li class="nav-list-item"><a href="{% url "tables0" %}">Ασθενείς (Πίνακας)</a></li>
                    <li class="nav-list-item"><a href="{% url "publishers" %}">Ασθενείς (Λίστα)</a></li>
					<li class="nav-list-item"><a href="{% url "person_list" %}">Ασθενείς (Λίστα2)</a></li>
					<li class="nav-list-item"><a href="{% url "people1" %}">Ασθενείς (Λίστα3)</a></li>
					<li class="nav-list-item"><a href="{% url "contact0" %}">contact0</a></li>
					<li class="nav-list-item"><a href="{% url "contact1" %}">contact1</a></li>
					<li class="nav-list-item"><a href="{% url "locations" %}">Locations</a></li>
                    <li class="divider"></li>
                    <li class="nav-list-item"><a href="{% url "MedMOHApp:list" %}">Ασθενείς (Λίστα2)</a></li>
                </ul>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}	

templates/base_forms.html
{% load i18n crispy_forms_tags %}

{% block base_content %}<div class="row">
    <div class="small-12 columns">
        <h2>{% trans 'Crispy forms Foundation sample' %}</h2>
        <h3 class="subheader">{% trans 'By form containers' %}</h3>
        
        {% comment %}{% with packages_versions=view.get_versions %}
        <ul>
            <li><small>django-crispy-forms=={{ packages_versions.django_crispy_forms }}</small></li>
            <li><small>crispy-forms-foundation=={{ packages_versions.crispy_forms_foundation }}</small></li>
        </ul>
        {% endwith %}
        <hr>{% endcomment %}
        

        {% crispy form %}
    </div>
</div>{% endblock %}

templates/char.html
{% extends 'base.html' %}

{% block content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>

<script src="http://yui.yahooapis.com/3.10.0/build/yui/yui-min.js"></script>

{{ chart.as_html }}
<p></p>
{{ chart1.as_html }}

{% endblock content %}

templates/example_form.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>

{% block content %}

{% load crispy_forms_tags %}
{% crispy example_form example_form.helper %}

{% endblock %}

templates/home.html
{% extends "_layouts/base.html" %}

{% block css %}
{{block.super}}
<style>
/* Move down content because we have a fixed navbar that is 50px tall */
body {
  padding-top: 50px;
  padding-bottom: 20px;
}
</style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}
<!-- This code is taken from http://getbootstrap.com/examples/jumbotron/ -->

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more »</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
      </div>
    </div>

{% endblock %}

templates/index.html
{% load i18n %}

{% block menu_item_contact %} class="active"{% endblock %}

{% block base_content %}<div class="row">
    <h2>Index des démos</h2>
    
    <hr>
</div>{% endblock %}

templates/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
        <!-- List of uploaded documents -->
        {% if documents %}
            <ul>
                {% for document in documents %}
                    <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "MedMOHApp:listdoc" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
    </body>

</html>

templates/tabs.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load staticfiles %}


{% block content1 %}
//<![CDATA[
{% block content %}

<script type="text/javascript" src="{% static 'crispy_forms_foundation/plugins.js' %}"></script>
        <div class="row">
    <div class="small-12 columns">
<script type="text/javascript">
$(document).ready(function() {
    $('form').abide_support_for_tabs();
});
</script>
{% crispy form %}
{% endblock %}
{% endblock %}

templates/template.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.BioExaminationId }} - {{ obj.examnameid }}<br />
    {% endfor %}
{% endblock %}